from domain.models.UsuarioModels import Usuario
from domain.models.EscolaModels import Escola
from domain.models.ProfessorModels import Professor
from domain.models.ProfessorEscolaModels import ProfessorEscola
from domain.models.TurmaModels import Turma
from domain.models.AlunoModels import Aluno
from domain.models.ConteudoModels import Conteudo
from domain.models.LivroModels import Livro
from domain.models.QuizModels import Quiz
from domain.models.QuestaoModels import Questao
from domain.models.ProgressoModels import Progresso
from domain.models.AvaliacaoIAModels import AvaliacaoIA
